-- Safe to rerun. Future schema changes should use versioned migrations.
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount_cents BIGINT NOT NULL CHECK(amount_cents > 0 AND amount_cents <= 99999999999),
    category VARCHAR(50) NOT NULL CHECK(length(trim(category)) BETWEEN 1 AND 50),
    note VARCHAR(500) NOT NULL DEFAULT '',
    date DATE NOT NULL CHECK(date BETWEEN DATE '0001-01-01' AND DATE '9999-12-31')
);
CREATE INDEX IF NOT EXISTS expenses_date ON expenses(date);
CREATE INDEX IF NOT EXISTS expenses_category_date ON expenses(category, date);
-- The server connects as the table owner; anonymous Supabase Data API clients
-- get no policies and cannot read/write this table. Dashboard access still works.
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS expenses_date_id ON expenses(date DESC, id DESC);
CREATE INDEX IF NOT EXISTS expenses_category_date_id ON expenses(category, date DESC, id DESC);
